"""One-time cleanup: remove old v3 JSON analysis data from tender_intelligence.

This script:
1. Clears all old tender_intelligence records (they use the deprecated v3 JSON format)
2. Resets business_fit_explanation on opportunities (will be regenerated by mini-summary)
3. Removes agent-uploaded documents (from bt_agent/merx_agent)

Run on server:
  docker compose -f docker-compose.prod.yml exec scraper-api python -m scripts.cleanup_old_analysis
Or directly:
  python scripts/cleanup_old_analysis.py
"""
import os
import sys

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def main():
    from sqlalchemy import create_engine, text

    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        pg_host = os.environ.get("POSTGRES_HOST", "localhost")
        pg_port = os.environ.get("POSTGRES_PORT", "5432")
        pg_db = os.environ.get("POSTGRES_DB", "leadharvest")
        pg_user = os.environ.get("POSTGRES_USER", "leadharvest")
        pg_pass = os.environ.get("POSTGRES_PASSWORD", "changeme_in_production")
        db_url = f"postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}"

    engine = create_engine(db_url)
    with engine.begin() as conn:
        # 1. Count old analysis records
        count = conn.execute(text("SELECT COUNT(*) FROM tender_intelligence")).scalar()
        print(f"Found {count} old analysis records")

        if count > 0:
            conn.execute(text("DELETE FROM tender_intelligence"))
            print(f"  Deleted {count} old analysis records")

        # 2. Clear old business_fit_explanation (will be regenerated)
        updated = conn.execute(
            text("UPDATE opportunities SET business_fit_explanation = NULL WHERE business_fit_explanation IS NOT NULL")
        ).rowcount
        print(f"Cleared business_fit_explanation on {updated} opportunities")

        # 3. Remove agent-uploaded documents
        agent_docs = conn.execute(
            text("DELETE FROM opportunity_documents WHERE url LIKE 'agent-upload://%' OR url LIKE 'upload://%'")
        ).rowcount
        print(f"Removed {agent_docs} agent-uploaded documents")

        # 4. Clean up AI usage log for old analyses
        usage = conn.execute(
            text("DELETE FROM ai_usage_log WHERE analysis_mode IN ('auto', 'auto_deep', 'quick', 'deep')")
        ).rowcount
        print(f"Cleared {usage} old AI usage records")

    print("\nCleanup complete.")


if __name__ == "__main__":
    main()
